name: Check doc

on:
  push:
    paths:
      # if new statements are added
      - 'src/lua/zencode_*'
      # if new documented statements are added
      - 'docs/examples/zencode_cookbook/*.zen'
      - 'docs/examples/zencode_cookbook/**/*.zen'

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Zenroom on linux
        run: |
          sudo apt install zsh jq luajit lua-cjson lua5.3 && make linux
          make needed-docs
