name: Check crypto

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Build Zenroom on linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install zsh jq meson && make linux
          make check-crypto
      - name: Build Zenroom on macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          pip install meson ninja
          make osx
          make check-osx
