name: Build cortex-arm target

on: [push, pull_request]

jobs:
  coverity-scan:
    runs-on: ubuntu-20.04
    steps:
      - uses: numworks/setup-arm-toolchain@2020-q4
      - name: checkout code
        uses: actions/checkout@v3
      - name: update dependencies
        run: |
          sudo apt update
      - name: install dependencies
        run: |
          sudo apt install zsh qemu-system-arm
      - name: download cmsis
        run: |
          curl -LO https://github.com/ARM-software/CMSIS_5/archive/refs/tags/5.7.0.tar.gz
          tar xvf 5.7.0.tar.gz -C lib
          mv lib/CMSIS_5-5.7.0 lib/cmsis
      - name: build cortex-arm target 
        run: |
          make cortex-arm
      - name: Run cortex-m check
        run: |
          make check-cortex-m
