name: Build and upload nightly to NPM
on:
  push:
    branches:
      - master 
    paths-ignore:
    - 'docs/**'
    - 'examples/**'
    - '*.md'
  pull_request:

env:
  EM_VERSION: latest
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/javascript
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
      - run: emcc -v
      - name: Install zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update; sudo apt-get install zsh meson ninja-build
      - run: yarn
      - run: yarn build
        env: 
          EMSCRIPTEN: ${{env.EMSDK}}/upstream/emscripten
      - run: yarn test
      - name: Run crypto tests
        working-directory: ./
        run: make check-js

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: bindings/javascript
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
      - name: Install zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update; sudo apt-get install zsh meson ninja-build
      - run: yarn
      - run: yarn build
        env: 
          EMSCRIPTEN: ${{ env.EMSDK }}/upstream/emscripten
      - name: Run yarn version to zenroom@next
        run: yarn version --new-version $(npm show zenroom version)-$(git rev-parse --short HEAD) --no-git-tag-version
      - run: npm publish . --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

